[[colors.indexed_colors]]
color = "#ffa066"
index = 16

[[colors.indexed_colors]]
color = "#ff5d62"
index = 17

[colors.bright]
black = "#a6a69c"
blue = "#7FB4CA"
cyan = "#7AA89F"
green = "#87a987"
magenta = "#938AA9"
red = "#E46876"
white = "#c5c9c5"
yellow = "#E6C384"

[colors.normal]
black = "#0c0b0b"
blue = "#8ba4b0"
cyan = "#8ea4a2"
green = "#8a9a7b"
magenta = "#a292a3"
red = "#c4746e"
white = "#C8C093"
yellow = "#c4b28a"

[colors.primary]
background = "#0a0a0a"
foreground = "#c5c9c5"

[colors.selection]
background = "#2d4f67"
foreground = "#c8c093"

[font]
size = 10

[font.bold]
family = "Jetbrains Mono NF"
style = "Bold"

[font.bold_italic]
family = "Jetbrains Mono NF"
style = "Bold Italic"

[font.italic]
family = "Jetbrains Mono NF"
style = "Italic"

[font.normal]
family = "Jetbrains Mono NF"
style = "Regular"

[window]
opacity = 0.90
