require('core.plugin_config.presence')
require('core.plugin_config.theme')
require('core.plugin_config.color-picker')
require('core.plugin_config.lualine')
require('core.plugin_config.treesitter')
require('core.plugin_config.nvim-tree')
